LANG_MAP = {
    # Русские
    "английский": "English",
    "немецкий": "German",
    "французский": "French",
    "испанский": "Spanish",
    "итальянский": "Italian",
    "китайский": "Chinese (Mandarin)",
    "японский": "Japanese",
    "корейский": "Korean",
    "португальский": "Portuguese",
    "польский": "Polish",
    "арабский": "Arabic",
    "турецкий": "Turkish",
    "хинди": "Hindi",
    "украинский": "Ukrainian",
    "чехский": "Czech",
    "голландский": "Dutch",
    "шведский": "Swedish",
    "норвежский": "Norwegian",
    "финский": "Finnish",
    "иврит": "Hebrew",

    # Английские
    "english": "English",
    "german": "German",
    "french": "French",
    "spanish": "Spanish",
    "italian": "Italian",
    "chinese": "Chinese (Mandarin)",
    "japanese": "Japanese",
    "korean": "Korean",
    "portuguese": "Portuguese",
    "polish": "Polish",
    "arabic": "Arabic",
    "turkish": "Turkish",
    "hindi": "Hindi",
    "ukrainian": "Ukrainian",
    "czech": "Czech",
    "dutch": "Dutch",
    "swedish": "Swedish",
    "norwegian": "Norwegian",
    "finnish": "Finnish",
    "hebrew": "Hebrew",
}


# Автоматически сгенерированные переменные из заголовков Google Sheets

NAME_MAP = {
    
    "на русском": "На русском",
    "на английском": "На английском",
}

SURNAME_MAP = {
    "на русском": "На русском",
    "на английском": "На английском",
}

ROLES_MAP = {
    "python developer": "Python Developer",
    "java developer": "Java Developer",
    "javascript developer": "JavaScript Developer",
    "typescript developer": "TypeScript Developer",
    "rust developer": "Rust Developer",
    "go developer": "Go Developer",
    "c++ developer": "C++ Developer",
    "c# developer": "C# Developer",
    "php developer": "PHP Developer",
    "kotlin developer": "Kotlin Developer",
    "swift developer": "Swift Developer",
    "frontend developer": "Frontend Developer",
    "backend developer": "Backend Developer",
    "fullstack developer": "Fullstack Developer",
    "mobile developer": "Mobile Developer",
    "ios developer": "iOS Developer",
    "android developer": "Android Developer",
    "blockchain developer": "Blockchain Developer",
    "smart contract engineer": "Smart Contract Engineer",
    "game developer": "Game Developer",
    "embedded developer": "Embedded Developer",
    "data engineer": "Data Engineer",
    "data scientist": "Data Scientist",
    "machine learning engineer": "Machine Learning Engineer",
    "mlops engineer": "MLOps Engineer",
    "ai engineer": "AI Engineer",
    "big data engineer": "Big Data Engineer",
    "bi developer": "BI Developer",
    "devops engineer": "DevOps Engineer",
    "site reliability engineer": "Site Reliability Engineer",
    "cloud engineer": "Cloud Engineer",
    "security engineer": "Security Engineer",
    "network engineer": "Network Engineer",
    "system administrator": "System Administrator",
    "qa manual engineer": "QA Manual Engineer",
    "qa automation engineer": "QA Automation Engineer",
    "test analyst": "Test Analyst",
    "performance engineer": "Performance Engineer",
    "business analyst": "Business Analyst",
    "system analyst": "System Analyst",
    "data analyst": "Data Analyst",
    "product analyst": "Product Analyst",
    "bi analyst": "BI Analyst",
    "1c analyst": "1C Analyst",
    "project manager": "Project Manager",
    "product manager": "Product Manager",
    "delivery manager": "Delivery Manager",
    "program manager": "Program Manager",
    "scrum master": "Scrum Master",
    "agile coach": "Agile Coach",
    "cto": "CTO",
    "tech lead": "Tech Lead",
    "team lead": "Team Lead",
    "ui/ux designer": "UI/UX Designer",
    "product designer": "Product Designer",
    "graphic designer": "Graphic Designer",
    "motion designer": "Motion Designer",
    "game designer": "Game Designer",
    "technical writer": "Technical Writer",
    "support engineer": "Support Engineer",
    "customer success manager": "Customer Success Manager",
    "salesforce developer": "Salesforce Developer",
    "salesforce administrator": "Salesforce Administrator",
    "salesforce consultant": "Salesforce Consultant",
    "salesforce architect": "Salesforce Architect",
    "integration architect": "Integration Architect",
    "solutions architect": "Solutions Architect",
    "enterprise architect": "Enterprise Architect",
    "application architect": "Application Architect",
    "data architect": "Data Architect",
    "cloud solutions architect": "Cloud Solutions Architect",
    "platform engineer": "Platform Engineer",
    "platform architect": "Platform Architect",
    "observability engineer": "Observability Engineer",
    "monitoring engineer": "Monitoring Engineer",
    "release manager": "Release Manager",
    "build engineer": "Build Engineer",
    "ci/cd engineer": "CI/CD Engineer",
    "configuration manager": "Configuration Manager",
    "infrastructure engineer": "Infrastructure Engineer",
    "infrastructure as code (iac) engineer": "Infrastructure as Code (IaC) Engineer",
    "finops engineer": "FinOps Engineer",
    "devsecops engineer": "DevSecOps Engineer",
    "aiops engineer": "AIOps Engineer",
    "analytics engineer": "Analytics Engineer",
    "dataops engineer": "DataOps Engineer",
    "data platform engineer": "Data Platform Engineer",
    "data warehouse architect": "Data Warehouse Architect",
    "etl developer": "ETL Developer",
    "data integration engineer": "Data Integration Engineer",
    "informatica developer": "Informatica Developer",
    "dbt developer": "DBT Developer",
    "airflow engineer": "Airflow Engineer",
    "database administrator (dba)": "Database Administrator (DBA)",
    "postgresql dba": "PostgreSQL DBA",
    "mysql dba": "MySQL DBA",
    "oracle dba": "Oracle DBA",
    "nosql engineer": "NoSQL Engineer",
    "elasticsearch engineer": "Elasticsearch Engineer",
    "kafka engineer": "Kafka Engineer",
    "stream processing engineer": "Stream Processing Engineer",
    "integration engineer": "Integration Engineer",
    "api developer": "API Developer",
    "api product manager": "API Product Manager",
    "api architect": "API Architect",
    "middleware (esb) engineer": "Middleware (ESB) Engineer",
    "ipaas engineer": "iPaaS Engineer",
    "mulesoft developer": "MuleSoft Developer",
    "boomi developer": "Boomi Developer",
    "sap abap developer": "SAP ABAP Developer",
    "sap bw/bi consultant": "SAP BW/BI Consultant",
    "sap basis administrator": "SAP Basis Administrator",
    "sap fico consultant": "SAP FICO Consultant",
    "sap sd consultant": "SAP SD Consultant",
    "sap mm consultant": "SAP MM Consultant",
    "sap hcm consultant": "SAP HCM Consultant",
    "sap successfactors consultant": "SAP SuccessFactors Consultant",
    "dynamics 365 developer (ce)": "Dynamics 365 Developer (CE)",
    "dynamics 365 developer (f&o)": "Dynamics 365 Developer (F&O)",
    "nav/business central developer": "NAV/Business Central Developer",
    "ax developer": "AX Developer",
    "dynamics consultant": "Dynamics Consultant",
    "oracle e-business suite developer": "Oracle E-Business Suite Developer",
    "oracle fusion cloud consultant": "Oracle Fusion Cloud Consultant",
    "oracle apex developer": "Oracle APEX Developer",
    "netsuite developer": "NetSuite Developer",
    "hubspot developer": "HubSpot Developer",
    "zoho crm developer": "Zoho CRM Developer",
    "magento/adobe commerce developer": "Magento/Adobe Commerce Developer",
    "shopify developer": "Shopify Developer",
    "woocommerce developer": "WooCommerce Developer",
    "bigcommerce developer": "BigCommerce Developer",
    "wordpress developer": "WordPress Developer",
    "drupal developer": "Drupal Developer",
    "joomla developer": "Joomla Developer",
    "web developer": "Web Developer",
    "web administrator": "Web Administrator",
    "flutter developer": "Flutter Developer",
    "react native developer": "React Native Developer",
    "xamarin developer": "Xamarin Developer",
    "unity developer": "Unity Developer",
    "unreal engine developer": "Unreal Engine Developer",
    "technical artist": "Technical Artist",
    "tools programmer": "Tools Programmer",
    "level designer": "Level Designer",
    "game producer": "Game Producer",
    "game qa engineer": "Game QA Engineer",
    "liveops engineer": "LiveOps Engineer",
    "ar/vr developer": "AR/VR Developer",
    "application security engineer": "Application Security Engineer",
    "penetration tester": "Penetration Tester",
    "red team engineer": "Red Team Engineer",
    "blue team analyst": "Blue Team Analyst",
    "soc analyst": "SOC Analyst",
    "incident response engineer": "Incident Response Engineer",
    "threat intelligence analyst": "Threat Intelligence Analyst",
    "grc analyst": "GRC Analyst",
    "iam engineer": "IAM Engineer",
    "cryptography engineer": "Cryptography Engineer",
    "pki engineer": "PKI Engineer",
    "privacy engineer": "Privacy Engineer",
    "compliance analyst (it)": "Compliance Analyst (IT)",
    "network security engineer": "Network Security Engineer",
    "voip engineer": "VoIP Engineer",
    "wireless network engineer": "Wireless Network Engineer",
    "sd-wan engineer": "SD-WAN Engineer",
    "storage engineer": "Storage Engineer",
    "virtualization engineer (vmware)": "Virtualization Engineer (VMware)",
    "windows systems engineer": "Windows Systems Engineer",
    "linux systems engineer": "Linux Systems Engineer",
    "exchange/office 365 engineer": "Exchange/Office 365 Engineer",
    "m365 administrator": "M365 Administrator",
    "sharepoint developer": "SharePoint Developer",
    "sharepoint administrator": "SharePoint Administrator",
    "collaboration engineer (slack/teams)": "Collaboration Engineer (Slack/Teams)",
    "help desk technician": "Help Desk Technician",
    "desktop support engineer": "Desktop Support Engineer",
    "field service engineer (it)": "Field Service Engineer (IT)",
    "itsm specialist": "ITSM Specialist",
    "servicenow developer": "ServiceNow Developer",
    "atlassian administrator (jira/confluence)": "Atlassian Administrator (Jira/Confluence)",
    "release train engineer (safe)": "Release Train Engineer (SAFe)",
    "product owner": "Product Owner",
    "technical program manager": "Technical Program Manager",
    "solutions consultant (pre-sales engineer)": "Solutions Consultant (Pre-Sales Engineer)",
    "customer success engineer": "Customer Success Engineer",
    "implementation engineer": "Implementation Engineer",
    "professional services engineer": "Professional Services Engineer",
    "technical account manager": "Technical Account Manager",
    "platform product manager": "Platform Product Manager",
    "growth engineer": "Growth Engineer",
    "experimentation engineer": "Experimentation Engineer",
    "search engineer (information retrieval)": "Search Engineer (Information Retrieval)",
    "relevance engineer": "Relevance Engineer",
    "adtech engineer": "AdTech Engineer",
    "marketing technologist (martech engineer)": "Marketing Technologist (MarTech Engineer)",
    "firmware engineer": "Firmware Engineer",
    "hardware engineer": "Hardware Engineer",
    "fpga engineer": "FPGA Engineer",
    "asic design engineer": "ASIC Design Engineer",
    "rtl design engineer": "RTL Design Engineer",
    "pcb design engineer": "PCB Design Engineer",
    "iot engineer": "IoT Engineer",
    "iot solutions architect": "IoT Solutions Architect",
    "robotics engineer": "Robotics Engineer",
    "dsp engineer (audio/signal processing)": "DSP Engineer (Audio/Signal Processing)",
    "nlp engineer": "NLP Engineer",
    "computer vision engineer": "Computer Vision Engineer",
    "speech recognition engineer": "Speech Recognition Engineer",
    "prompt engineer": "Prompt Engineer",
    "llm engineer": "LLM Engineer",
    "llmops engineer": "LLMOps Engineer",
    "applied scientist (ml)": "Applied Scientist (ML)",
    "research scientist (ai/ml)": "Research Scientist (AI/ML)",
    "data governance lead": "Data Governance Lead",
    "data steward": "Data Steward",
    "data quality engineer": "Data Quality Engineer",
    "data privacy officer": "Data Privacy Officer",
    "gis developer": "GIS Developer",
    "gis analyst": "GIS Analyst",
    "bioinformatics engineer": "Bioinformatics Engineer",
    "healthcare interoperability engineer (hl7/fhir)": "Healthcare Interoperability Engineer (HL7/FHIR)",
    "edi developer": "EDI Developer",
    "hpc engineer (high performance computing)": "HPC Engineer (High Performance Computing)",
    "devrel engineer (developer relations)": "DevRel Engineer (Developer Relations)",
    "technical trainer": "Technical Trainer",
    "financial systems engineer": "Financial Systems Engineer",
    "payment systems engineer": "Payment Systems Engineer",
    "blockchain protocol engineer": "Blockchain Protocol Engineer",
    "web3 frontend engineer": "Web3 Frontend Engineer",
    "defi engineer": "DeFi Engineer",
    "1c developer": "1C Developer",
    "talend developer": "Talend Developer",
    "ssis developer": "SSIS Developer",
}

LOCATION_MAP = {
    "страна": "Страна",
    "город": "Город",
}

GRADE_MAP = {
    "intern": "Intern",
    "junior": "Junior",
    "middle": "Middle",
    "senior": "Senior",
    "lead": "Lead",
    "principal": "Principal",
    "expert": "Expert",
    "architect": "Architect",
    "manager": "Manager",
    "head": "Head",
    "c-level": "C-level",
}

PROGRAM_LANG_MAP = {
    "python": "Python",
    "javascript": "JavaScript",
    "typescript": "TypeScript",
    "java": "Java",
    "c": "C",
    "c++": "C++",
    "c#": "C#",
    "go": "Go",
    "rust": "Rust",
    "kotlin": "Kotlin",
    "swift": "Swift",
    "php": "PHP",
    "ruby": "Ruby",
    "scala": "Scala",
    "r": "R",
    "sql": "SQL",
    "perl": "Perl",
    "solidity": "Solidity",
    "dart": "Dart",
    "assembly": "Assembly",
    "objective-c": "Objective-C",
    "vb.net": "VB.NET",
    "groovy": "Groovy",
    "d": "D",
    "zig": "Zig",
    "nim": "Nim",
    "crystal": "Crystal",
    "v": "V",
    "haskell": "Haskell",
    "ocaml": "OCaml",
    "f#": "F#",
    "clojure": "Clojure",
    "common lisp": "Common Lisp",
    "scheme": "Scheme",
    "elixir": "Elixir",
    "erlang": "Erlang",
    "racket": "Racket",
    "purescript": "PureScript",
    "idris": "Idris",
    "elm": "Elm",
    "bash": "Bash",
    "posix sh": "POSIX sh",
    "powershell": "PowerShell",
    "lua": "Lua",
    "tcl": "Tcl",
    "julia": "Julia",
    "matlab": "MATLAB",
    "octave": "Octave",
    "fortran": "Fortran",
    "cobol": "COBOL",
    "ada": "Ada",
    "delphi (object pascal)": "Delphi (Object Pascal)",
    "pl/sql": "PL/SQL",
    "t-sql": "T-SQL",
    "cypher": "Cypher",
    "gremlin": "Gremlin",
    "mdx": "MDX",
    "dax": "DAX",
    "haxe": "Haxe",
    "gdscript": "GDScript",
    "qml": "QML",
    "kotlin multiplatform (kmp)": "Kotlin Multiplatform (KMP)",
    "jruby": "JRuby",
    "jython": "Jython",
    "pig latin": "Pig Latin",
    "hiveql": "HiveQL",
    "verilog": "Verilog",
    "systemverilog": "SystemVerilog",
    "vhdl": "VHDL",
    "q#": "Q#",
    "wolfram language": "Wolfram Language",
    "abap": "ABAP",
    "apex": "Apex",
    "xquery": "XQuery",
    "xpath": "XPath",
    "xslt": "XSLT",
    "sas": "SAS",
    "stata": "Stata",
    "spss": "SPSS",
    "vyper": "Vyper",
    "move": "Move",
    "cairo": "Cairo",
    "pact": "Pact",
    "michelson": "Michelson",
    "plutus": "Plutus",
    "motoko": "Motoko",
    "cuda": "CUDA",
    "opencl": "OpenCL",
    "smalltalk": "Smalltalk",
    "prolog": "Prolog",
    "mercury": "Mercury",
    "reasonml/rescript": "ReasonML/Rescript",
    "hack (hhvm)": "Hack (HHVM)",
    "coldfusion (cfml)": "ColdFusion (CFML)",
    "autohotkey": "AutoHotkey",
    "labview g": "LabVIEW G",
    "ladder logic (iec 61131-3)": "Ladder Logic (IEC 61131-3)",
    "logo": "Logo",
}

FRAMEWORKS_MAP = {
    "react": "React",
    "angular": "Angular",
    "vue.js": "Vue.js",
    "next.js": "Next.js",
    "redux": "Redux",
    "tailwind css": "Tailwind CSS",
    "bootstrap": "Bootstrap",
    "express": "Express",
    "nestjs": "NestJS",
    "django": "Django",
    "flask": "Flask",
    "fastapi": "FastAPI",
    "ruby on rails": "Ruby on Rails",
    "laravel": "Laravel",
    "symfony": "Symfony",
    "spring boot": "Spring Boot",
    "asp.net core": "ASP.NET Core",
    "entity framework": "Entity Framework",
    "gin": "Gin",
    "actix-web": "Actix-web",
    "axum": "Axum",
    "flutter": "Flutter",
    "react native": "React Native",
    "tensorflow": "TensorFlow",
    "pytorch": "PyTorch",
    "keras": "Keras",
    "scikit-learn": "scikit-learn",
    "opencv": "OpenCV",
    "langchain": "LangChain",
    "apache spark": "Apache Spark",
    "airflow": "Airflow",
    "jest": "Jest",
    "cypress": "Cypress",
    "selenium": "Selenium",
    "junit": "JUnit",
    "pytest": "PyTest",
    "graphql": "GraphQL",
    "grpc": "gRPC",
    "hardhat": "Hardhat",
    "truffle": "Truffle",
    "unity": "Unity",
    "unreal engine": "Unreal Engine",
    "svelte": "Svelte",
    "sveltekit": "SvelteKit",
    "nuxt.js": "Nuxt.js",
    "nuxt": "Nuxt",
    "remix": "Remix",
    "solidjs": "SolidJS",
    "preact": "Preact",
    "alpine.js": "Alpine.js",
    "stimulus": "Stimulus",
    "astro": "Astro",
    "mobx": "MobX",
    "zustand": "Zustand",
    "recoil": "Recoil",
    "redux toolkit": "Redux Toolkit",
    "rtk query": "RTK Query",
    "rxjs": "RxJS",
    "pinia": "Pinia",
    "vuex": "Vuex",
    "ngrx": "NgRx",
    "tanstack query (react query)": "TanStack Query (React Query)",
    "swr": "SWR",
    "react router": "React Router",
    "vue router": "Vue Router",
    "angular router": "Angular Router",
    "next router": "Next Router",
    "formik": "Formik",
    "react hook form": "React Hook Form",
    "yup": "Yup",
    "zod": "Zod",
    "joi": "Joi",
    "veevalidate": "VeeValidate",
    "class-validator": "class-validator",
    "sass": "Sass",
    "less": "Less",
    "postcss": "PostCSS",
    "styled components": "Styled Components",
    "emotion": "Emotion",
    "css modules": "CSS Modules",
    "stitches": "Stitches",
    "material ui (mui)": "Material UI (MUI)",
    "ant design": "Ant Design",
    "chakra ui": "Chakra UI",
    "mantine": "Mantine",
    "radix ui": "Radix UI",
    "shadcn/ui": "shadcn/ui",
    "semantic ui": "Semantic UI",
    "foundation": "Foundation",
    "bulma": "Bulma",
    "primereact": "PrimeReact",
    "primeng": "PrimeNG",
    "primevue": "PrimeVue",
    "vuetify": "Vuetify",
    "quasar": "Quasar",
    "element plus": "Element Plus",
    "headless ui": "Headless UI",
    "bootstrapvue": "BootstrapVue",
    "d3.js": "D3.js",
    "chart.js": "Chart.js",
    "echarts": "ECharts",
    "highcharts": "Highcharts",
    "recharts": "Recharts",
    "victory": "Victory",
    "nivo": "Nivo",
    "plotly.js": "Plotly.js",
    "three.js": "Three.js",
    "babylon.js": "Babylon.js",
    "pixijs": "PixiJS",
    "mapbox gl js": "Mapbox GL JS",
    "leaflet": "Leaflet",
    "cesiumjs": "CesiumJS",
    "vite": "Vite",
    "webpack": "Webpack",
    "rollup": "Rollup",
    "parcel": "Parcel",
    "babel": "Babel",
    "swc": "SWC",
    "esbuild": "esbuild",
    "fastify": "Fastify",
    "koa": "Koa",
    "hapi": "Hapi",
    "adonisjs": "AdonisJS",
    "sails.js": "Sails.js",
    "feathersjs": "FeathersJS",
    "loopback": "LoopBack",
    "keystonejs": "KeystoneJS",
    "strapi": "Strapi",
    "medusajs": "MedusaJS",
    "prisma": "Prisma",
    "typeorm": "TypeORM",
    "sequelize": "Sequelize",
    "mongoose": "Mongoose",
    "knex.js": "Knex.js",
    "objection.js": "Objection.js",
    "drizzle orm": "Drizzle ORM",
    "django rest framework": "Django REST Framework",
    "starlette": "Starlette",
    "tornado": "Tornado",
    "sanic": "Sanic",
    "pyramid": "Pyramid",
    "falcon": "Falcon",
    "bottle": "Bottle",
    "flask-restful": "Flask-RESTful",
    "flask-restx": "Flask-RESTX",
    "celery": "Celery",
    "sqlalchemy": "SQLAlchemy",
    "alembic": "Alembic",
    "pydantic": "Pydantic",
    "requests": "Requests",
    "aiohttp": "aiohttp",
    "httpx": "httpx",
    "scrapy": "Scrapy",
    "spring security": "Spring Security",
    "spring data": "Spring Data",
    "spring cloud": "Spring Cloud",
    "hibernate": "Hibernate",
    "micronaut": "Micronaut",
    "quarkus": "Quarkus",
    "vert.x": "Vert.x",
    "play framework": "Play Framework",
    "dropwizard": "Dropwizard",
    "mapstruct": "MapStruct",
    "lombok": "Lombok",
    "netty": "Netty",
    "blazor": "Blazor",
    ".net maui": ".NET MAUI",
    "wpf": "WPF",
    "dapper": "Dapper",
    "automapper": "AutoMapper",
    "serilog": "Serilog",
    "nlog": "NLog",
    "xunit": "xUnit",
    "nunit": "NUnit",
    "masstransit": "MassTransit",
    "mediatr": "MediatR",
    "ocelot": "Ocelot",
    "polly": "Polly",
    "fiber (go)": "Fiber (Go)",
    "echo (go)": "Echo (Go)",
    "chi (go)": "Chi (Go)",
    "beego": "Beego",
    "buffalo": "Buffalo",
    "gorilla mux": "Gorilla Mux",
    "gorm": "GORM",
    "sqlx (go)": "sqlx (Go)",
    "cobra (go)": "Cobra (Go)",
    "viper (go)": "Viper (Go)",
    "zap (go)": "Zap (Go)",
    "logrus": "Logrus",
    "rocket (rust)": "Rocket (Rust)",
    "warp (rust)": "Warp (Rust)",
    "hyper (rust)": "Hyper (Rust)",
    "tonic (rust)": "Tonic (Rust)",
    "tower (rust)": "Tower (Rust)",
    "serde (rust)": "Serde (Rust)",
    "diesel (rust)": "Diesel (Rust)",
    "seaorm (rust)": "SeaORM (Rust)",
    "reqwest (rust)": "Reqwest (Rust)",
    "tracing (rust)": "Tracing (Rust)",
    "clap (rust)": "Clap (Rust)",
    "codeigniter": "CodeIgniter",
    "yii": "Yii",
    "cakephp": "CakePHP",
    "phalcon": "Phalcon",
    "slim (php)": "Slim (PHP)",
    "doctrine orm": "Doctrine ORM",
    "monolog": "Monolog",
    "hanami": "Hanami",
    "sinatra": "Sinatra",
    "grape": "Grape",
    "sidekiq": "Sidekiq",
    "resque": "Resque",
    "sequel (ruby)": "Sequel (Ruby)",
    "capybara": "Capybara",
    "rspec": "RSpec",
    "apache flink": "Apache Flink",
    "kafka streams": "Kafka Streams",
    "apache beam": "Apache Beam",
    "apache storm": "Apache Storm",
    "apache samza": "Apache Samza",
    "apache pulsar": "Apache Pulsar",
    "dbt": "dbt",
    "prefect": "Prefect",
    "dagster": "Dagster",
    "luigi": "Luigi",
    "meltano": "Meltano",
    "delta lake": "Delta Lake",
    "apache hudi": "Apache Hudi",
    "apache iceberg": "Apache Iceberg",
    "great expectations": "Great Expectations",
    "soda core": "Soda Core",
    "feast": "Feast",
    "xgboost": "XGBoost",
    "lightgbm": "LightGBM",
    "catboost": "CatBoost",
    "transformers (hugging face)": "Transformers (Hugging Face)",
    "diffusers (hf)": "Diffusers (HF)",
    "spacy": "spaCy",
    "nltk": "NLTK",
    "stanza": "Stanza",
    "gensim": "Gensim",
    "sentencetransformers": "SentenceTransformers",
    "opennmt": "OpenNMT",
    "fairseq": "Fairseq",
    "ray": "Ray",
    "dask": "Dask",
    "dask-ml": "Dask-ML",
    "modin": "Modin",
    "mlflow": "MLflow",
    "kubeflow": "Kubeflow",
    "weights & biases (wandb)": "Weights & Biases (wandb)",
    "onnx runtime": "ONNX Runtime",
    "tensorrt": "TensorRT",
    "openvino": "OpenVINO",
    "deepspeed": "DeepSpeed",
    "vllm": "vLLM",
    "text generation inference (tgi)": "Text Generation Inference (TGI)",
    "peft": "PEFT",
    "bitsandbytes": "bitsandbytes",
    "faiss": "FAISS",
    "milvus (client libs)": "Milvus (client libs)",
    "chroma": "Chroma",
    "haystack": "Haystack",
    "llamaindex": "LlamaIndex",
    "guidance": "Guidance",
    "albumentations": "Albumentations",
    "detectron2": "Detectron2",
    "mmdetection": "MMDetection",
    "ultralytics yolo": "Ultralytics YOLO",
    "mediapipe": "MediaPipe",
    "mocha": "Mocha",
    "chai": "Chai",
    "jasmine": "Jasmine",
    "vitest": "Vitest",
    "ava": "AVA",
    "playwright": "Playwright",
    "puppeteer": "Puppeteer",
    "testcafe": "TestCafe",
    "robot framework": "Robot Framework",
    "hypothesis": "Hypothesis",
    "pact": "Pact",
    "k6": "k6",
    "gatling": "Gatling",
    "jmeter": "JMeter",
    "locust": "Locust",
    "artillery": "Artillery",
    "supertest": "Supertest",
    "mockito": "Mockito",
    "spock": "Spock",
    "testng": "TestNG",
    "apollo client": "Apollo Client",
    "apollo server": "Apollo Server",
    "relay": "Relay",
    "graphene (python)": "Graphene (Python)",
    "gqlgen (go)": "gqlgen (Go)",
    "retrofit": "Retrofit",
    "okhttp": "OkHttp",
    "feign": "Feign",
    "axios": "axios",
    "superagent": "superagent",
    "protobuf": "Protobuf",
    "apache avro": "Apache Avro",
    "apache thrift": "Apache Thrift",
    "passport.js": "Passport.js",
    "nextauth.js": "NextAuth.js",
    "devise (ruby)": "Devise (Ruby)",
    "spring security (java)": "Spring Security (Java)",
    "jwt (jose/jsonwebtoken)": "JWT (jose/jsonwebtoken)",
    "rq (python)": "RQ (Python)",
    "dramatiq": "Dramatiq",
    "bullmq": "BullMQ",
    "rabbitmq clients": "RabbitMQ clients",
    "kafka client libraries": "Kafka client libraries",
    "ionic": "Ionic",
    "capacitor": "Capacitor",
    "cordova": "Cordova",
    "nativescript": "NativeScript",
    "jetpack compose": "Jetpack Compose",
    "room (android)": "Room (Android)",
    "koin": "Koin",
    "dagger/hilt": "Dagger/Hilt",
    "swiftui": "SwiftUI",
    "combine": "Combine",
    "alamofire": "Alamofire",
    "electron": "Electron",
    "tauri": "Tauri",
    "qt": "Qt",
    "gtk": "GTK",
    "wxwidgets": "wxWidgets",
    "avalonia ui": "Avalonia UI",
    "wpf (legacy)": "WPF (legacy)",
    "godot": "Godot",
    "phaser": "Phaser",
    "cocos2d-x": "Cocos2d-x",
    "libgdx": "libGDX",
    "ogre3d": "Ogre3D",
    "opentelemetry (sdk)": "OpenTelemetry (SDK)",
    "prometheus client libraries": "Prometheus client libraries",
    "jaeger clients": "Jaeger clients",
}

TECH_MAP = {
    "postgresql": "PostgreSQL",
    "mysql": "MySQL",
    "sqlite": "SQLite",
    "oracle database": "Oracle Database",
    "microsoft sql server": "Microsoft SQL Server",
    "mongodb": "MongoDB",
    "redis": "Redis",
    "elasticsearch": "Elasticsearch",
    "clickhouse": "ClickHouse",
    "snowflake": "Snowflake",
    "bigquery": "BigQuery",
    "amazon redshift": "Amazon Redshift",
    "apache kafka": "Apache Kafka",
    "rabbitmq": "RabbitMQ",
    "aws": "AWS",
    "microsoft azure": "Microsoft Azure",
    "google cloud platform": "Google Cloud Platform",
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "helm": "Helm",
    "terraform": "Terraform",
    "ansible": "Ansible",
    "github actions": "GitHub Actions",
    "gitlab ci/cd": "GitLab CI/CD",
    "jenkins": "Jenkins",
    "prometheus": "Prometheus",
    "grafana": "Grafana",
    "elk stack": "ELK Stack",
    "efk stack": "EFK Stack",
    "nginx": "Nginx",
    "apache http server": "Apache HTTP Server",
    "oauth2": "OAuth2",
    "openid connect": "OpenID Connect",
    "jwt": "JWT",
    "maven": "Maven",
    "gradle": "Gradle",
    "npm": "npm",
    "yarn": "Yarn",
    "pip": "pip",
    "cargo": "Cargo",
    "composer": "Composer",
    "power bi": "Power BI",
    "tableau": "Tableau",
    "qlik sense": "Qlik Sense",
    "wordpress": "WordPress",
    "drupal": "Drupal",
    "magento": "Magento",
    "shopify": "Shopify",
    "salesforce": "Salesforce",
    "sap": "SAP",
    "1c:enterprise": "1C:Enterprise",
    "microsoft dynamics 365": "Microsoft Dynamics 365",
    "linux": "Linux",
    "windows": "Windows",
    "macos": "macOS",
    "android": "Android",
    "ios": "iOS",
    "mariadb": "MariaDB",
    "amazon aurora": "Amazon Aurora",
    "aurora postgresql": "Aurora PostgreSQL",
    "aurora mysql": "Aurora MySQL",
    "azure sql database": "Azure SQL Database",
    "cloud spanner": "Cloud Spanner",
    "oracle autonomous database": "Oracle Autonomous Database",
    "ibm db2": "IBM Db2",
    "sap hana": "SAP HANA",
    "neo4j": "Neo4j",
    "cassandra": "Cassandra",
    "couchbase": "Couchbase",
    "couchdb": "CouchDB",
    "dynamodb": "DynamoDB",
    "scylladb": "ScyllaDB",
    "rocksdb": "RocksDB",
    "leveldb": "LevelDB",
    "hbase": "HBase",
    "opensearch": "OpenSearch",
    "opensearch dashboards": "OpenSearch Dashboards",
    "open distro for elasticsearch": "Open Distro for Elasticsearch",
    "sphinx search": "Sphinx Search",
    "manticore search": "Manticore Search",
    "solr": "Solr",
    "timescaledb": "TimescaleDB",
    "influxdb": "InfluxDB",
    "victoriametrics": "VictoriaMetrics",
    "prometheus tsdb (standalone)": "Prometheus TSDB (standalone)",
    "questdb": "QuestDB",
    "druid": "Druid",
    "apache pinot": "Apache Pinot",
    "apache hudi": "Apache Hudi",
    "apache iceberg": "Apache Iceberg",
    "delta lake": "Delta Lake",
    "trino": "Trino",
    "presto": "Presto",
    "apache drill": "Apache Drill",
    "apache arrow": "Apache Arrow",
    "parquet": "Parquet",
    "orc": "ORC",
    "minio": "MinIO",
    "ceph": "Ceph",
    "hdfs": "HDFS",
    "glusterfs": "GlusterFS",
    "nfs": "NFS",
    "aws s3": "AWS S3",
    "google cloud storage": "Google Cloud Storage",
    "azure blob storage": "Azure Blob Storage",
    "efs": "EFS",
    "ebs": "EBS",
    "azure files": "Azure Files",
    "apache pulsar": "Apache Pulsar",
    "activemq": "ActiveMQ",
    "zeromq": "ZeroMQ",
    "nats": "NATS",
    "mqtt (eclipse mosquitto)": "MQTT (Eclipse Mosquitto)",
    "amazon sqs": "Amazon SQS",
    "amazon sns": "Amazon SNS",
    "google pub/sub": "Google Pub/Sub",
    "azure service bus": "Azure Service Bus",
    "kafka connect": "Kafka Connect",
    "debezium": "Debezium",
    "apache nifi": "Apache NiFi",
    "streamsets": "StreamSets",
    "confluent platform": "Confluent Platform",
    "apache flink": "Apache Flink",
    "apache beam": "Apache Beam",
    "apache storm": "Apache Storm",
    "apache samza": "Apache Samza",
    "envoy proxy": "Envoy Proxy",
    "haproxy": "HAProxy",
    "traefik": "Traefik",
    "caddy": "Caddy",
    "kong": "Kong",
    "tyk": "Tyk",
    "wso2 api manager": "WSO2 API Manager",
    "apigee": "Apigee",
    "amazon api gateway": "Amazon API Gateway",
    "azure api management": "Azure API Management",
    "istio": "Istio",
    "linkerd": "Linkerd",
    "consul service mesh": "Consul Service Mesh",
    "kuma": "Kuma",
    "containerd": "containerd",
    "cri-o": "CRI-O",
    "podman": "Podman",
    "docker compose": "Docker Compose",
    "openshift": "OpenShift",
    "rancher": "Rancher",
    "k3s": "K3s",
    "kind (kubernetes in docker)": "Kind (Kubernetes in Docker)",
    "microk8s": "MicroK8s",
    "eks": "EKS",
    "gke": "GKE",
    "aks": "AKS",
    "harbor": "Harbor",
    "jfrog artifactory": "JFrog Artifactory",
    "sonatype nexus repository": "Sonatype Nexus Repository",
    "pulumi": "Pulumi",
    "aws cloudformation": "AWS CloudFormation",
    "aws cdk": "AWS CDK",
    "cdk for terraform (cdktf)": "CDK for Terraform (CDKTF)",
    "packer": "Packer",
    "kustomize": "Kustomize",
    "opa (open policy agent)": "OPA (Open Policy Agent)",
    "kyverno": "Kyverno",
    "hashicorp vault": "HashiCorp Vault",
    "aws kms": "AWS KMS",
    "azure key vault": "Azure Key Vault",
    "google cloud kms": "Google Cloud KMS",
    "sops (mozilla-sops)": "SOPS (mozilla-sops)",
    "argo cd": "Argo CD",
    "flux cd": "Flux CD",
    "spinnaker": "Spinnaker",
    "circleci": "CircleCI",
    "travis ci": "Travis CI",
    "azure devops pipelines": "Azure DevOps Pipelines",
    "bitbucket pipelines": "Bitbucket Pipelines",
    "teamcity": "TeamCity",
    "bazel": "Bazel",
    "cmake": "CMake",
    "make": "Make",
    "ninja": "Ninja",
    "msbuild": "MSBuild",
    "opentelemetry": "OpenTelemetry",
    "jaeger": "Jaeger",
    "zipkin": "Zipkin",
    "loki": "Loki",
    "tempo": "Tempo",
    "elastic apm": "Elastic APM",
    "sentry": "Sentry",
    "datadog": "Datadog",
    "new relic": "New Relic",
    "splunk": "Splunk",
    "sumo logic": "Sumo Logic",
    "graylog": "Graylog",
    "tomcat": "Tomcat",
    "jetty": "Jetty",
    "uwsgi": "uWSGI",
    "gunicorn": "Gunicorn",
    "nginx unit": "Nginx Unit",
    "iis": "IIS",
    "keycloak": "Keycloak",
    "auth0": "Auth0",
    "okta": "Okta",
    "aws cognito": "AWS Cognito",
    "dex": "Dex",
    "hashicorp boundary": "HashiCorp Boundary",
    "pnpm": "pnpm",
    "poetry": "Poetry",
    "pipenv": "Pipenv",
    "nuget": "NuGet",
    "ivy": "Ivy",
    "gradle kotlin dsl": "Gradle Kotlin DSL",
    "yarn berry": "Yarn Berry",
    "looker": "Looker",
    "looker studio": "Looker Studio",
    "apache superset": "Apache Superset",
    "metabase": "Metabase",
    "redash": "Redash",
    "sisense": "Sisense",
    "microstrategy": "MicroStrategy",
    "mode analytics": "Mode Analytics",
    "sigma computing": "Sigma Computing",
    "amundsen": "Amundsen",
    "datahub": "DataHub",
    "apache atlas": "Apache Atlas",
    "collibra": "Collibra",
    "alation": "Alation",
    "great expectations": "Great Expectations",
    "soda core": "Soda Core",
    "monte carlo data": "Monte Carlo Data",
    "strapi": "Strapi",
    "contentful": "Contentful",
    "sanity": "Sanity",
    "ghost cms": "Ghost CMS",
    "keystone cms": "Keystone CMS",
    "headless wordpress": "Headless WordPress",
    "bigcommerce": "BigCommerce",
    "shopware": "Shopware",
    "woocommerce": "WooCommerce",
    "prestashop": "PrestaShop",
    "odoo": "Odoo",
    "servicenow": "ServiceNow",
    "jira": "Jira",
    "jira service management": "Jira Service Management",
    "confluence": "Confluence",
    "notion": "Notion",
    "clickup": "ClickUp",
    "zendesk": "Zendesk",
    "freshdesk": "Freshdesk",
    "hubspot": "HubSpot",
    "zoho crm": "Zoho CRM",
    "oracle cloud infrastructure (oci)": "Oracle Cloud Infrastructure (OCI)",
    "ibm cloud": "IBM Cloud",
    "alibaba cloud": "Alibaba Cloud",
    "digitalocean": "DigitalOcean",
    "hetzner cloud": "Hetzner Cloud",
    "ovhcloud": "OVHcloud",
    "cloudflare": "Cloudflare",
    "cloudflare workers": "Cloudflare Workers",
    "akamai": "Akamai",
    "fastly": "Fastly",
    "vercel": "Vercel",
    "netlify": "Netlify",
    "fly.io": "Fly.io",
    "render": "Render",
    "aws lambda": "AWS Lambda",
    "azure functions": "Azure Functions",
    "google cloud functions": "Google Cloud Functions",
    "knative": "Knative",
    "serverless framework": "Serverless Framework",
    "aws sam": "AWS SAM",
    "aws route 53": "AWS Route 53",
    "cloudflare dns": "Cloudflare DNS",
    "ns1": "NS1",
    "bind9": "Bind9",
    "coredns": "CoreDNS",
    "cloudflare cdn": "Cloudflare CDN",
    "aws cloudfront": "AWS CloudFront",
    "azure cdn": "Azure CDN",
    "fastly cdn": "Fastly CDN",
    "akamai cdn": "Akamai CDN",
    "cloudflare waf": "Cloudflare WAF",
    "sonarqube": "SonarQube",
    "snyk": "Snyk",
    "trivy": "Trivy",
    "grype": "Grype",
    "clair": "Clair",
    "anchore": "Anchore",
    "dependabot": "Dependabot",
    "renovate": "Renovate",
    "owasp zap": "OWASP ZAP",
    "burp suite": "Burp Suite",
    "nessus": "Nessus",
    "qualys": "Qualys",
    "openscap": "OpenSCAP",
    "gitleaks": "Gitleaks",
    "semgrep": "Semgrep",
    "bandit": "Bandit",
    "checkov": "Checkov",
    "terrascan": "Terrascan",
    "prometheus operator": "Prometheus Operator",
    "grafana loki stack": "Grafana Loki Stack",
    "keda": "KEDA",
    "cert-manager": "cert-manager",
    "external-dns": "external-dns",
    "velero": "Velero",
    "longhorn": "Longhorn",
    "metallb": "MetalLB",
    "karpenter": "Karpenter",
    "cluster autoscaler": "Cluster Autoscaler",
    "pagerduty": "PagerDuty",
    "opsgenie": "Opsgenie",
    "xmatters": "xMatters",
    "victorops (splunk on-call)": "VictorOps (Splunk On-Call)",
    "firehydrant": "FireHydrant",
    "restic": "Restic",
    "borgbackup": "BorgBackup",
    "rclone": "Rclone",
    "velero (k8s backup)": "Velero (K8s backup)",
    "sendgrid": "SendGrid",
    "mailgun": "Mailgun",
    "amazon ses": "Amazon SES",
    "postfix": "Postfix",
    "exim": "Exim",
    "jupyter": "Jupyter",
    "jupyterhub": "JupyterHub",
    "zeppelin": "Zeppelin",
    "dvc": "DVC",
    "lakefs": "LakeFS",
    "mlflow": "MLflow",
    "weights & biases": "Weights & Biases",
    "informatica powercenter": "Informatica PowerCenter",
    "talend": "Talend",
    "fivetran": "Fivetran",
    "stitch": "Stitch",
    "mulesoft": "MuleSoft",
    "boomi": "Boomi",
    "make (integromat)": "Make (Integromat)",
    "zapier": "Zapier",
    "n8n": "n8n",
    "apache camel": "Apache Camel",
    "launchdarkly": "LaunchDarkly",
    "unleash": "Unleash",
    "optimizely": "Optimizely",
    "growthbook": "GrowthBook",
    "electron": "Electron",
    "tauri": "Tauri",
    "qt": "Qt",
    "gtk": "GTK",
    "wxwidgets": "wxWidgets",
    "avalonia ui": "Avalonia UI",
    "vmware esxi": "VMware ESXi",
    "kvm": "KVM",
    "hyper-v": "Hyper-V",
    "proxmox ve": "Proxmox VE",
    "virtualbox": "VirtualBox",
    "freebsd": "FreeBSD",
    "openbsd": "OpenBSD",
    "fedora": "Fedora",
    "ubuntu": "Ubuntu",
    "debian": "Debian",
    "alpine linux": "Alpine Linux",
    "centos stream": "CentOS Stream",
    "rocky linux": "Rocky Linux",
    "rhel": "RHEL",
    "suse linux enterprise": "SUSE Linux Enterprise",
    "eslint": "ESLint",
    "prettier": "Prettier",
    "black (python)": "Black (Python)",
    "ruff": "Ruff",
    "flake8": "Flake8",
    "checkstyle": "Checkstyle",
    "spotbugs": "SpotBugs",
    "pylint": "Pylint",
    "shellcheck": "ShellCheck",
    "hadolint": "hadolint",
    "pre-commit": "pre-commit",
}

PRODUCT_INDUSTRIES_MAP = {
    "banking": "Banking",
    "fintech": "FinTech",
    "insurance": "Insurance",
    "retail": "Retail",
    "e-commerce": "E-commerce",
    "telecom": "Telecom",
    "healthcare": "Healthcare",
    "pharma": "Pharma",
    "oil & gas": "Oil & Gas",
    "energy": "Energy",
    "manufacturing": "Manufacturing",
    "automotive": "Automotive",
    "logistics": "Logistics",
    "transportation": "Transportation",
    "supply chain": "Supply Chain",
    "travel": "Travel",
    "tourism": "Tourism",
    "aviation": "Aviation",
    "government": "Government",
    "public sector": "Public Sector",
    "education": "Education",
    "edtech": "EdTech",
    "media": "Media",
    "entertainment": "Entertainment",
    "streaming": "Streaming",
    "gaming": "Gaming",
    "construction": "Construction",
    "engineering": "Engineering",
    "real estate": "Real Estate",
    "agriculture": "Agriculture",
    "foodtech": "FoodTech",
    "cybersecurity": "Cybersecurity",
    "ai": "AI",
    "big data": "Big Data",
    "research": "Research",
    "startups": "Startups",
    "innovation": "Innovation",
    "r&d": "R&D",
    "capital markets": "Capital Markets",
    "asset management": "Asset Management",
    "wealth management": "Wealth Management",
    "payments": "Payments",
    "lending & microfinance": "Lending & Microfinance",
    "regtech": "RegTech",
    "legaltech": "LegalTech",
    "hrtech": "HRTech",
    "martech": "MarTech",
    "adtech": "AdTech",
    "proptech": "PropTech",
    "sportstech": "SportsTech",
    "hospitality (hotels & restaurants)": "Hospitality (Hotels & Restaurants)",
    "consumer packaged goods (cpg)": "Consumer Packaged Goods (CPG)",
    "fashion & apparel": "Fashion & Apparel",
    "beauty & cosmetics": "Beauty & Cosmetics",
    "food & beverage (f&b)": "Food & Beverage (F&B)",
    "mining & metals": "Mining & Metals",
    "chemicals": "Chemicals",
    "pulp & paper": "Pulp & Paper",
    "textiles": "Textiles",
    "aerospace & defense": "Aerospace & Defense",
    "spacetech": "SpaceTech",
    "utilities (water & wastewater)": "Utilities (Water & Wastewater)",
    "waste management": "Waste Management",
    "environmental tech (envtech)": "Environmental Tech (EnvTech)",
    "climatetech": "ClimateTech",
    "carbon accounting": "Carbon Accounting",
    "renewable energy (wind/solar)": "Renewable Energy (Wind/Solar)",
    "grid & smart metering": "Grid & Smart Metering",
    "maritime & shipping": "Maritime & Shipping",
    "ports & terminals": "Ports & Terminals",
    "railways": "Railways",
    "public transit": "Public Transit",
    "postal & parcel": "Postal & Parcel",
    "warehousing & fulfillment tech": "Warehousing & Fulfillment Tech",
    "semiconductor": "Semiconductor",
    "electronics manufacturing": "Electronics Manufacturing",
    "additive manufacturing (3d printing)": "Additive Manufacturing (3D Printing)",
    "biotech": "Biotech",
    "medtech (medical devices)": "MedTech (Medical Devices)",
    "diagnostics & labs": "Diagnostics & Labs",
    "digital health & telemedicine": "Digital Health & Telemedicine",
    "agritech": "AgriTech",
    "aquaculture & fisheries": "Aquaculture & Fisheries",
    "forestry": "Forestry",
    "corporate learning & l&d": "Corporate Learning & L&D",
    "publishing": "Publishing",
    "broadcasting": "Broadcasting",
    "musictech": "MusicTech",
    "esports": "Esports",
    "betting & igaming": "Betting & iGaming",
    "smart city": "Smart City",
    "public safety & law enforcement": "Public Safety & Law Enforcement",
    "nonprofit & ngos": "Nonprofit & NGOs",
    "civictech": "CivicTech",
    "smart home & iot": "Smart Home & IoT",
    "robotics": "Robotics",
}



PORTFOLIO_MAP = {
    "github": "GitHub",
    "gitlab": "GitLab",
    "bitbucket": "Bitbucket",
    "linkedin": "LinkedIn",
    "stack overflow": "Stack Overflow",
    "kaggle": "Kaggle",
    "hugging face": "Hugging Face",
    "leetcode": "LeetCode",
    "codeforces": "Codeforces",
    "hackerrank": "HackerRank",
    "dribbble": "Dribbble",
    "behance": "Behance",
    "upwork": "Upwork",
    "fiverr": "Fiverr",
    "toptal": "Toptal",
    "medium": "Medium",
    "dev.to": "Dev.to",
    "habr": "Habr",
    "notion": "Notion",
    "tilda": "Tilda",
    "wix": "Wix",
    "github pages": "GitHub Pages",
    "youtube": "YouTube",
    "vimeo": "Vimeo",
}

WORK_TIME_MAP = {
    "full-time": "Full-time",
    "part-time": "Part-time",
    "project-based": "Project-based",
}

WORK_FORM_MAP = {
    "оформление в штат": "Оформление в штат",
    "самозанятый": "Самозанятый",
    "ип": "ИП",
    "b2b contract / outstaff": "B2B contract / Outstaff",
}

CONTACTS_MAP = {
    "telegram": "Telegram",
    "github/gitlab": "GitHub/GitLab",
    "телефон": "Телефон",
    "e-mail": "E-mail",
    "linkedin": "LinkedIn",
    "skype": "Skype",
    "whatsapp": "WhatsApp",
    "viber": "Viber",
    "discord": "Discord",
    "slack": "Slack",
    "microsoft teams": "Microsoft Teams",
    "zoom": "Zoom",
    "google meet": "Google Meet",
    "facebook": "Facebook",
    "instagram": "Instagram",
    "x (twitter)": "X (Twitter)",
    "vk": "VK",
    "tiktok": "TikTok",
    "reddit": "Reddit",
    "stack overflow": "Stack Overflow",
    "habr career": "Habr Career",
}



AVAILABILITY_MAP = {
    "actively looking": "Actively looking",
    "open to offers": "Open to offers",
    "not looking": "Not looking",
    "unavailable": "Unavailable",
    "freelance only": "Freelance only",
    "available from [date]": "Available from [date]",
    "interviewing": "Interviewing",
}

